### ISSUE TITLE
MO5 reset when launching any game

### ISSUE THREAD

**Issue by kamuikun42** [Zlika/theodore#15]
Hello,

I have a major issue on RetroArch 1.7.8 with the Theodore core on Android aa64 (GPD XD+).

When trying to launch any MO5 game, the MO5 reset.

I've tried the same thing on PC and it is working fine.

Can you please fix this? Thanks.

**Comment by Zlika** [comment]
Hi! Thank you for reporting this issue. I've just tried to launch an MO5 game with the lattest 1.7.8 version (2nd hotfix) on my android phone and it's working ok (but I don't know if I'm running the 32b or 64b version). You only have this problem with the MO5?

**Comment by kamuikun42** [comment]
After a bit more testing, it seems this happen only when launching a game from the micro SD card. I've tried to copy the .k7 to the internal storage and now it is working fine.
I think you can close this issue. Sorry for the trouble!

**Comment by Zlika** [comment]
Ok, but it's still an interesting problem though: are disk images (fd/sap) or cartridges correctly loaded from the sd card? From the emulator point of view there should be no difference between sd card and internal storage. Did you gave Retroarch the right to access the sd card? Have you tried with other cores?

**Comment by kamuikun42** [comment]
I do have storage access permission on RetroArch. I've only tried with .K7 files.
I think this is an issue since KitKat: Native apps (non-Java) such as RetroArch can't write to the external SD card unless it is formated as internal storage. Mine is set as portable storage to be able to use it on other devices.

**Comment by Zlika** [comment]
Ok. So I close the issue. Have fun using Theodore.
