### ISSUE TITLE
Permission to add Theodore to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [Zlika/theodore#20]
Hi there @Zlika,

we would like to seek your permission to include Theodore as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by Zlika** [comment]
Hi @twinaphex,
Thank you for asking my permission.
Of course I agree to make this core freely available for RA on steam if the GPL license is ok for this use case.
Regards

**Comment by twinaphex** [comment]
Thank you. And yes, it will be completely GPL.
