### ISSUE TITLE
[Switch] Theodore is broken

### ISSUE THREAD

**Issue by cucholix** [Zlika/theodore#23]
Hi, updating my cores today was testing that everything was in order, and when booting a game on Theodore it crash retroarch and kick me out the system menu, the oldest version I tested is from may-01-2020 (the oldest available too), I can test older versions if you point me to them, so we can narrow the issue.

Regards.

**Comment by Zlika** [comment]
Hi!
Thanks for reporting this issue.
I changed the pixel format in https://github.com/Zlika/theodore/commit/9c8af6f92d01237a06a0afae2cbdadc5f6d71468 to make the core usable on memory constrained devices. Could you try to test before/after this commit? Thanks.

**Comment by cucholix** [comment]
I don't know how to build .nro on Switch saddly :(

**Comment by Zlika** [comment]
Do you remember what was the date of the last working version you used?
Also, the change of the pixel format broke the compatibility of the save state files: could you check your Retroarch is not configured to autoload the last save state of the game you are starting?

**Comment by cucholix** [comment]
I have save autoload disabled, the last time I used Theodore was around december 2019, not quite sure to be honest.

**Comment by Zlika** [comment]
I figured out how to build .nro files.
Please download the following binary: https://easyupload.io/k68rwt (build just before the change of the pixel format), rename the file as theodore_libretro_libnx.nro and copy it on your switch to test it.
If it is working, than try to do the same with this binary (build just after the change of the pixel format): https://easyupload.io/hehgvv
These nro files have been built against RetroArch v1.8.9.
Let me know if one of them is working.

**Comment by cucholix** [comment]
hi, just tested and none of them are working... they all just crash on startup

**Comment by Zlika** [comment]
That's weird because before the commit where I changed the pixel format, I have to go back in time until may/june 2019 to find (small) code changes. So if the core was working end of 2019 I don't know why the first binary in my previous message is not working.
Can you try a clean re-install of RA? Maybe the core's configuration file is corrupted.

**Comment by cucholix** [comment]
Tried with a fresh retroarch.cfg and retroarch-core-options.cfg and it still crashing on startup. I make sure there's not save files or save states, or options/core overrides...

**Comment by cucholix** [comment]
Doing more testing in the core (the most recent one available on the online updater), I can load and start the core just fine, the bios screen display correctly, but at the moment to load a .fd game it crashes RA.

**Comment by Zlika** [comment]
Interesting.
Let's try an older version from february 2019: https://easyupload.io/h81bqk

**Comment by cucholix** [comment]
february 2019 version doesn't even allows to load/start the core, it crashes right away. 

A test we could try is try to load the game from console (with the most recent release), if you give me the commands I can try to load the game from bios screen and see what happen.

**Comment by Zlika** [comment]
Which version of RA do you have? I compiled against v1.8.9.
I don't think you can load a game file once the core is started.

**Comment by Zlika** [comment]
I mean, technically it should be possible because the libretro API allows that, but I don't think you can do that from RA.

**Comment by cucholix** [comment]
I'm using 1.8.9 too, it's weird because I made a build as old as 2018 few commits after Switch/libnx support and theodore keeps crashing, that's why I though that maybe it could be a problem with the RA version we are compiling against (1.8.9), since in 2018 RA side suffered many changes...

**Comment by Zlika** [comment]
Could you try to clean install an older version from https://buildbot.libretro.com/stable/ ?
The oldest version including the theodore core is this one: https://buildbot.libretro.com/stable/1.7.6/nintendo/switch/libnx/

**Comment by Ploggy** [comment]
I'm having the same issue (using latest core build from the updater) Loading a .Sap rom. 
Its possible to Start Core, which brings up the T08 Thomson screen. But theres no way to load a game from that screen so thats as far as it gets.
Same game loads fine from PC version of RA.

I noticed "Auto run game" is disabled by default in the core's options (enabling it does fix the issue tho)

I tried the 1.7.6 version linked above.. loading a game boots to the TO8 Thomson screen but joycon buttons are unresponsive although the switch touchscreen works so its possible to tap the screen to boot thea game :)

**Comment by Zlika** [comment]
Could you try the different versions to find the first one that is not working?

**Comment by cucholix** [comment]
For me 1.7.8 is the first one that crash when try to load content, 1.7.7 works fine apparently but you don't have button response, also I get this image in: 
![photo_2020-06-28_16-41-02](https://user-images.githubusercontent.com/16081693/85957772-3e35d080-b95e-11ea-91c6-9b0df0ed1f1c.jpg)

**Comment by Zlika** [comment]
Version 1.7.7 was released on May 10th 2019. From this date, I only made a few PS2 specific changes in the code, so I really don't understand what can be the problem.
I also don't understand why the buttons are not responding on "working" versions. Were you ever able to correctly use this core on Switch?
Do you find similar problems with other cores?

**Comment by cucholix** [comment]
The not working buttons was a problem with all the homebrew apps, it was due Nintendo changing the way HID was handled in older firmwares, but it's unrelated to your code, it's because the RA version was too old and didn't had the HID fix in place.

So to your question, yes, I was able to correctly use theodore on Switch when it was using older firmware, older RA, etc... 
I've audit every core on Switch and find this issue only on theodore (well except blueMSX that has been broken forever but we at last have fmsx as alternative)

**Comment by cucholix** [comment]
I was wrong, 1.7.6 was the last working build, I can load games just fine, and the cursor works, still you can't play because the buttons don't respond (old RA running on newest Switch firmware).
![photo_2020-06-28_17-41-31](https://user-images.githubusercontent.com/16081693/85958922-6bd34780-b967-11ea-816c-5999d37ae59d.jpg)

**Comment by cucholix** [comment]
Here are the crash reports that throw me, not sure why they are 2
[01593462778_0100c1300bbc6000.log](https://github.com/Zlika/theodore/files/4847898/01593462778_0100c1300bbc6000.log)
[01593462779_0100c1300bbc6000.log](https://github.com/Zlika/theodore/files/4847899/01593462779_0100c1300bbc6000.log)

**Comment by cucholix** [comment]
The core is working now with build from 7-7-20
👍

**Comment by Zlika** [comment]
The bug should be fixed by 04572cb9e241cadbc4887e213abe62de3ae65f7b , 94c292070272e52d81da06cda39edfcc73301fdd and a2f469a42617c13bfbdf8c72cc7632e7ecea953f.

**Comment by Zlika** [comment]
Thank you very much @cucholix for reporting and then helping me locate and fix this nasty bug.
The root problem was that on Nintendo Switch it seems that you cannot have two file handles on the same file.
