### ISSUE TITLE
[Wii Feature Request] Wiiflow Lite plugin

### ISSUE THREAD

**Issue by Edu789** [Zlika/theodore#24]
The core freeintv don't work as Wiiflow plugins, when entering the game he goes back to the Wiiflow Lite menu...

**Comment by Zlika** [comment]
Hi @Edu789. The freeintv repository is here: https://github.com/libretro/FreeIntv

**Comment by Zlika** [comment]
According to your other bug report https://github.com/libretro/RetroArch/issues/11281 it seems to be a problem affecting lots of different cores, so it's maybe a problem on RA and/or Wiiflow. Let me know if I have to do something on my side, but I do not use wiiflow, so without even a core dump I don't know what to do.

**Comment by Edu789** [comment]
I was wrong, it's the Theodore core and not Intellivision's...
The problem is the retroarch itself and not wiiflow, it only lists the games and has support for skins, various colors of the retroarch work normal in wiiflow
