### ISSUE TITLE
Problème identification du modele

### ISSUE THREAD

**Issue by z3tof** [Zlika/theodore#25]
Je viens de tester Theodore avec Rexalbox 7 et il semblerait qu'il y ait un petit problème avec l'identification du modèle basé sur le nom du fichier pour le to770 : mon fichier contient la chaîne to770 et il lance le modèle to7. Je suis bien en auto dans libreretro.
Sinon, parfait pour voyager dans le temps ! ;-)
Zetof

**Comment by Zlika** [comment]
Merci pour ce retour. Je regarde ça dès que possible.

**Comment by Zlika** [comment]
J'ai fait un essai et le mode TO7/70 est bien détecté. Attention il faut bien mettre to770 dans le nom, où la dernière lettre est un zéro et pas un o.

**Comment by z3tof** [comment]
Bizarre, je viens de refaire un essai et il ne me lance toujours pas le to770... C'est pourtant bien un o minuscule et un zéro pour le 70...
Je viens même d'enlever complètement le modèle et il le lance le modèle to7...

Tu as fait le test avec recalbox 7 ?

**Comment by z3tof** [comment]
Arf, je viens de comprendre : j'utilise des fichiers zippés et j'ai renommé le nom de l'archive avec to770 et non pas le nom du fichier contenu dans l'archive qui avait toujours que to7 dans le nom...

Désolé, ce n'est pas un bug... Juste une mauvaise utilisation de ma part...

Je réitère cependant ce que je disais dans mon premier post : parfait pour remonter dans le temps... 
Merci pour ce port !

**Comment by Zlika** [comment]
Ok. En effet c'est le nom du fichier dézippé qui est important, pas le zip, car la décompression est faite par Retroarch et le core ne voit que le fichier dézippé.
Content que l'émulateur plaise, c'est le but ! :-)
