### ISSUE TITLE
Space key on MO5 does not respond

### ISSUE THREAD

**Issue by Kamarad22** [Zlika/theodore#6]
Hello,
Under Retroach/Retropie Linux (and perhaps others OS?), when theodore_rom is set to "MO5", all the keyboard operates correctly, excepted the "space" key which does not respond at all, even when all Retroarch gamepad and/or hotkeys are off (i.e option "game focus on" selected, which turn off every call to external options thru specific keys).   The problem is that some older games, which run only on MO5 (and not on any other flavour) sometimes absolutely need the space key to play. The linux keyboard driver (udev) seems to operate correctly though, as the "fast forward" option , which is attached in retroarch.cfg to the "space" key, operates normally (of course when "game focus off" is selected).
Thanks!
BTW, nice work!!!

**Comment by Zlika** [comment]
Ooops... Stupid error in the keyboard mapping. Thanks for reporting it. Problem fixed in HEAD version. The libretro-buildbot will compile and make it available soon.

**Comment by Kamarad22** [comment]
Great! Thanks! Will try it ASAP available.
