### ISSUE TITLE
Autorun of loaded contents 

### ISSUE THREAD

**Issue by Kamarad22** [Zlika/theodore#7]
Hello,
Would be nice to have an option like theodore_autorun = true which would automatically, depending on flavour:
- Select the "B" option on TO8 menu
- Type in a run" followed by <enter> on MO5
this way, a content could be launched automatically.
PS: I tried this with the savestates, which works fine manually, but does not seems to respond to savestate_auto_load = "true"

**Comment by Zlika** [comment]
Hi,
Using the "autostart" button to simulate RUN" on MO5 was on my todo list, but I didn't thought adding an "Autostart" option to the core, thanks for the idea.

**Comment by Zlika** [comment]
Done. Please test let me know.

**Comment by Kamarad22** [comment]
So far, so good! Runs perfectly on MO5 and T08. I did not have the opportunity to test it on another flavour, though. Thanks!
