### ISSUE TITLE
TOx - No Sound in Yeti - Pulsar - Eliminator (Loriciels) games

### ISSUE THREAD

**Issue by MaRvIn054** [Zlika/theodore#8]
Hello,
first, hats off for this awsome project. I was thinking about something similar, and I found your work which  exactly meets my needs. I've implemented your Theodore core in my arcade cabinet powered by a Raspberry pi running Retropie.
I think I've found a bug in the TO8 flavor, the Loriciels Hits (Yéti, Pulsar, Eliminator) have no sound in games.
Interestingly, the MO5 versions of the games do have sound. Tested under DCMOTO, I can hear sound in TO8 for those games.
Maybe something not emulated properly on TO flavors? I could help to debug this issue but I'm not sure where to start...
Again, big thanks for this great project 👍 

Best Regards,
MaRvIn054.

**Comment by Zlika** [comment]
Problem fixed. These games use a really weird way of producing sound: instead of writing the sound sample in the required register, they use another register to mute/unmute the audio output. And Theodore wasn't emulating this mute feature.
Thanks for reporting this issue.
